# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4699772f61a89fb635966dceef81c4ab8c7c45a01a7d6c6f947d19f9ab56e35c7e48a394a15a370e7c33e429752161f5508c0e728639d3d73682155c428371a

test:
  secret_key_base: 2a6d0ed20a2921c8ed781b6fa7a4ecfd867aeda38ed6cd62c3bec2ce8f80791fd333721f6228cbb9f99832028beb17d28dfe6293cd478cae52e5abcd75e48f5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
